default: &default
 adapter: postgresql
 pool: 5
 timeout: 5000

development:
 adapter: postgresql
 encoding: unicode
 database: url_shortener_dev
 pool: 5


test:
 adapter: postgresql
 encoding: unicode
 database: url_shortener_test
 pool: 5
